/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.4.1 busy-janay
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This is the cellular IOT config
 */
export interface CellularIoTConfig { 
    imsi?: string;
    /**
     * on your device. This is the primary identifier for your device on the network.  The IMEI number is the unique ID for your hardware as
     */
    imei?: string;
}

