/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.2.3 lower-elian
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This is the metadata for a Cellular IoT device connected via an APN.
 */
export interface CellularIoTMetadata { 
    gatewayId?: string;
    allocatedIp?: string;
    allocatedAt?: string;
    cellId?: string;
    /**
     * the provider in use.
     */
    mcc?: number;
    mnc?: number;
    country?: string;
    network?: string;
    countryCode?: string;
    lastUpdate?: string;
}

