/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.13 interdependent-karson
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The firmware management settings for a collection can either be \"disabled\", ie there is no firmware management for this collection, \"collection\"; devices are managed through the settings on the collection or \"device\" where each device is configured individual.
 */
export type CollectionFirmwareFirmwareManagement = 'unspecified' | 'disabled' | 'collection' | 'device';

export const CollectionFirmwareFirmwareManagement = {
    Unspecified: 'unspecified' as CollectionFirmwareFirmwareManagement,
    Disabled: 'disabled' as CollectionFirmwareFirmwareManagement,
    Collection: 'collection' as CollectionFirmwareFirmwareManagement,
    Device: 'device' as CollectionFirmwareFirmwareManagement
};

