/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.5 contented-jamila
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Create a new firmware image
 */
export interface CreateFirmwareBody { 
    image?: string;
    version?: string;
    filename?: string;
    tags?: { [key: string]: string; };
}

