/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.9.6 authoritarian-betty
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageTransport } from './messageTransport';
import { DeviceConfig } from './deviceConfig';
import { DeviceMetadata } from './deviceMetadata';
import { FirmwareMetadata } from './firmwareMetadata';


/**
 * This a device
 */
export interface Device { 
    /**
     * The device ID is assigned by the backend.
     */
    deviceId?: string;
    collectionId?: string;
    /**
     * Tags are metadata for the device that you can set. These are just strings.
     */
    tags?: { [key: string]: string; };
    firmware?: FirmwareMetadata;
    config?: DeviceConfig;
    metadata?: DeviceMetadata;
    lastGatewayId?: string;
    lastTransport?: MessageTransport;
    lastReceived?: string;
    lastPayload?: string;
}
export namespace Device {
}


