/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.2.4 curable-andres
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CellularIoTConfig } from './cellularIoTConfig';


/**
 * This is the configuration for the device via the various gateways.
 */
export interface DeviceConfig { 
    ciot?: CellularIoTConfig;
}

