/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.8.0 indecipherable-ferman
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This is the statistics for a single device
 */
export interface DeviceStats { 
    bytesUpstreamMb?: number;
    bytesDownstreamMb?: number;
    messagesUpstream?: number;
    messagesDownstream?: number;
    sessionCount?: number;
}

