/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.4 pettish-alleen
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type GatewayStatus = 'unknown' | 'offline' | 'online';

export const GatewayStatus = {
    Unknown: 'unknown' as GatewayStatus,
    Offline: 'offline' as GatewayStatus,
    Online: 'online' as GatewayStatus
};

