/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.3 pitch-dark-elza
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Metadata for devices connected via user-managed gateways. This metadata shows the configuration for the last message transmission
 */
export interface GatewayDeviceMetadata { 
    gatewayId?: string;
    lastUpdate?: string;
    params?: { [key: string]: string; };
}

