/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.2.3 lower-elian
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A gateway is a connection between devices and Span
 */
export interface Gateway { 
    gatewayId?: string;
    collectionId?: string;
    networkId?: string;
    tags?: { [key: string]: string; };
}

