/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.2 subversive-jamila
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type GatewayType = 'unknown' | 'ciot' | 'inet' | 'lora' | 'openthread' | 'zigbee' | 'matter' | 'custom';

export const GatewayType = {
    Unknown: 'unknown' as GatewayType,
    Ciot: 'ciot' as GatewayType,
    Inet: 'inet' as GatewayType,
    Lora: 'lora' as GatewayType,
    Openthread: 'openthread' as GatewayType,
    Zigbee: 'zigbee' as GatewayType,
    Matter: 'matter' as GatewayType,
    Custom: 'custom' as GatewayType
};

