/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.2.4 curable-andres
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageDownstream } from './messageDownstream';


/**
 * Response object when listing downstream messages
 */
export interface ListDownstreamMessagesResponse { 
    messages?: Array<MessageDownstream>;
}

