/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.0 convulsive-launa
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OutputLogEntry } from './outputLogEntry';


/**
 * List logs for output
 */
export interface OutputLogResponse { 
    logs?: Array<OutputLogEntry>;
}

