/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.11 evasive-governor
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OutputType = 'undefined' | 'webhook' | 'udp' | 'mqtt' | 'ifttt';

export const OutputType = {
    Undefined: 'undefined' as OutputType,
    Webhook: 'webhook' as OutputType,
    Udp: 'udp' as OutputType,
    Mqtt: 'mqtt' as OutputType,
    Ifttt: 'ifttt' as OutputType
};

