/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.4.0 lean-joline
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OutputMessageType = 'unknown' | 'keepalive' | 'data';

export const OutputMessageType = {
    Unknown: 'unknown' as OutputMessageType,
    Keepalive: 'keepalive' as OutputMessageType,
    Data: 'data' as OutputMessageType
};

