/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.5 contented-jamila
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Output types available   - undefined: The undefined output type is an invalid type
 */
export type OutputType = 'undefined' | 'webhook' | 'udpout' | 'mqttclient' | 'ifttt' | 'mqttbroker';

export const OutputType = {
    Undefined: 'undefined' as OutputType,
    Webhook: 'webhook' as OutputType,
    Udpout: 'udpout' as OutputType,
    Mqttclient: 'mqttclient' as OutputType,
    Ifttt: 'ifttt' as OutputType,
    Mqttbroker: 'mqttbroker' as OutputType
};

