/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.7 prized-adelbert
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldMask } from './fieldMask';


export interface SystemInfoResponse { 
    version?: string;
    buildDate?: string;
    releaseName?: string;
    defaultFieldMask?: FieldMask;
    forcedFieldMask?: FieldMask;
}

